### ISSUE TITLE
Share format

### ISSUE THREAD

**Issue by fela** [LorisPolenz/semantIQ#3]
FIrst step brainstorm different ideas

**Comment by LorisPolenz** [comment]
### share results using a url with all the relevant information encoded in base64

Either a string such as `12;3;4;coconut` can be encoded, with each semicolon separated value has a meaning. i.e (attempts, correct, max_correct, last_word)

The string then is encoded into base64 and appended to the url

https://cool.project/share/`MTI7Mzs0O2NvY29udXQK`

On opening the website, the string can be decoded and displayed to the user.

Users could alter the values in the base64 for encoded strings.

**Comment by amoeri** [comment]
I was thinking more of a string like:
I scored 3 points in 5 tries on todays semantIQ.app puzzle. Can you beat this?

**Comment by LorisPolenz** [comment]
Also good idea, could be done effortlessly as well.

**Comment by amoeri** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
seems to have ok browser support for text

**Comment by fela** [comment]
Done
